# Base configuration template for training and simulation
mode: train
run_id: default-run
logs_dir: logs
artifacts_dir: artifacts
seasonality_log_level: INFO
# Rate limiter configuration for outbound signals
# max_signals_per_sec: 0 disables limiting
max_signals_per_sec: 0.0
backoff_base_s: 2.0
max_backoff_s: 60.0
execution_profile: MKT_OPEN_NEXT_H1
execution_params:
  slippage_bps: 0.0
  limit_offset_bps: 0.0  # e.g. 25 for 0.25% offset when using LIMIT_MID_BPS
  ttl_steps: 0           # e.g. 5 to cancel after 5 simulation steps
  tif: GTC               # e.g. IOC or FOK
execution_config:
  notional_threshold: 10000.0
  large_order_algo: TWAP
  pov:
    participation: 0.10
    child_interval_s: 60
    min_child_notional: 20.0

# Optional path to 168 hourly liquidity multipliers (indexed by UTC hour-of-week;
# values clamped to [0.1, 10.0])
liquidity_seasonality_path: "configs/liquidity_latency_seasonality.json"
# Optional SHA256 hash of the above liquidity multipliers for integrity checking
liquidity_seasonality_hash: null
# Optional path to 168 hourly liquidity overrides multiplied with the above multipliers
liquidity_seasonality_override_path: null
# Optional path to 168 hourly latency multipliers (indexed by UTC hour-of-week;
# values clamped to [0.1, 10.0])
latency_seasonality_path: "configs/liquidity_latency_seasonality.json"
# Set false to ignore liquidity and latency multipliers
use_seasonality: true

market: spot  # or futures

data:
  timeframe: "1m"  # symbols are loaded from data/universe/symbols.json

model:
  algo: "ppo"
  params: {}

quantizer:
  filters_path: "binance_filters.json"
  strict: true
  enforce_percent_price_by_side: true
  auto_refresh_days: 30
  refresh_on_start: false

fees:
  maker_bps: 1.0
  taker_bps: 5.0
  use_bnb_discount: false
  maker_discount_mult: 1.0
  taker_discount_mult: 1.0

slippage:
  k: 0.8
  min_half_spread_bps: 0.0
  default_spread_bps: 2.0
  eps: 1e-12

latency:
  base_ms: 250
  jitter_ms: 50
  spike_p: 0.01
  spike_mult: 5.0
  timeout_ms: 2500
  retries: 1
  seed: 0  # RNG seed; seasonality multipliers do not affect RNG state

risk:
  enabled: true
  max_abs_position_qty: 0.0
  max_abs_position_notional: 0.0
  max_order_notional: 0.0
  max_orders_per_min: 60
  max_orders_window_s: 60
  daily_loss_limit: 0.0
  pause_seconds_on_violation: 300
  daily_reset_utc_hour: 0

# See ../docs/no_trade.md for details
no_trade:
  funding_buffer_min: 0
  daily_utc: []
  custom_ms: []
  dynamic_guard:
    enable: false
    sigma_window: 120
    atr_window: 14
    vol_abs: null
    vol_pctile: 0.99
    spread_abs_bps: null
    spread_pctile: 0.99
    hysteresis: 0.1
    cooldown_bars: 10
    log_reason: true

components:
  market_data:
    target: impl_offline_data:OfflineCSVBarSource
    params:
      paths: []
      timeframe: "1m"
  executor:
    target: impl_sim_executor:SimExecutor
    params:
      symbol: "BTCUSDT"
  feature_pipe:
    target: feature_pipe:FeaturePipe
    params: {}
  policy:
    target: strategies.momentum:MomentumStrategy
    params: {}
  risk_guards:
    target: impl_risk_basic:RiskBasicImpl
    params: {}
  backtest_engine:
    target: service_backtest:ServiceBacktest
    params: {}
