mode: eval
run_id: eval-run
logs_dir: logs
artifacts_dir: artifacts
input:
  trades_path: "data/trades.csv"
components:
  market_data:
    target: impl_offline_data:OfflineCSVBarSource
    params:
      paths: ["data/eval.csv"]
      timeframe: "1m"
  executor:
    target: impl_sim_executor:SimExecutor
    params:
      symbol: "BTCUSDT"
  feature_pipe:
    target: feature_pipe:FeaturePipe
    params: {}
  strategy:
    target: strategies.momentum:MomentumStrategy
    params: {}
  risk_guards:
    target: impl_risk_basic:RiskBasicImpl
    params: {}
  backtest_engine:
    target: service_backtest:ServiceBacktest
    params: {}
