mode: live
run_id: live-run
logs_dir: logs
artifacts_dir: artifacts
seasonality_log_level: INFO
# Runtime settings are defined in runtime.yaml
runtime_config: runtime.yaml
execution_config:
  notional_threshold: 10000.0
  large_order_algo: TWAP
  pov:
    participation: 0.10
    child_interval_s: 60
    min_child_notional: 20.0
max_signals_per_sec: 5.0
backoff_base_s: 2.0
max_backoff_s: 60.0
timing:
  enforce_closed_bars: true
  timeframe_ms: 60000
  close_lag_ms: 2000
clock_sync:
  refresh_sec: 300        # How often to resync clocks in seconds
  warn_threshold_ms: 500  # Log warning if drift exceeds this many milliseconds
  kill_threshold_ms: 2000 # Terminate if drift exceeds this many milliseconds
  max_step_ms: 1000       # Max single adjustment step in milliseconds
  attempts: 5             # Number of sync attempts before giving up
ttl:
  enabled: false
  ttl_seconds: 60
  out_csv: null
  dedup_persist: null
api:
  api_key: null
  api_secret: null
data:
  symbols: ["BTCUSDT"]
  timeframe: "1m"
# Optional path to 168 hourly liquidity multipliers (indexed by UTC hour-of-week;
# values clamped to [0.1, 10.0])
liquidity_seasonality_path: "configs/liquidity_latency_seasonality.json"
# Optional SHA256 hash of the above liquidity multipliers for integrity checking
liquidity_seasonality_hash: null
# Optional path to 168 hourly liquidity overrides multiplied with the above multipliers
liquidity_seasonality_override_path: null
# Optional path to 168 hourly latency multipliers (indexed by UTC hour-of-week;
# values clamped to [0.1, 10.0])
latency_seasonality_path: "configs/liquidity_latency_seasonality.json"
# Set false to ignore liquidity and latency multipliers
use_seasonality: true
latency:
  base_ms: 250
  jitter_ms: 50
  spike_p: 0.01
  spike_mult: 5.0
  timeout_ms: 2500
  retries: 1
  seed: 0  # RNG seed; seasonality multipliers do not affect RNG state
pipeline:
  enabled: true
  stages:
    closed_bar:
      enabled: true
    windows:
      enabled: true
    anomaly:
      enabled: true
    extreme:
      enabled: true
    policy:
      enabled: true
    risk:
      enabled: true
    publish:
      enabled: true
components:
  market_data:
    target: impl_binance_public:BinancePublicBarSource
    params:
      timeframe: "1m"
  executor:
    target: impl_sim_executor:SimExecutor
    params:
      symbol: "BTCUSDT"
  feature_pipe:
    target: feature_pipe:FeaturePipe
    params: {}
  policy:
    target: strategies.momentum:MomentumStrategy
    params: {}
  risk_guards:
    target: impl_risk_basic:RiskBasicImpl
    params: {}
