mode: live
run_id: live-run
logs_dir: logs
artifacts_dir: artifacts
seasonality_log_level: INFO
execution_config:
  notional_threshold: 10000.0
  large_order_algo: TWAP
  pov:
    participation: 0.10
    child_interval_s: 60
    min_child_notional: 20.0
max_signals_per_sec: 5.0
backoff_base_s: 2.0
max_backoff_s: 60.0
timing:
  enforce_closed_bars: true
  timeframe_ms: 60000
  close_lag_ms: 2000
clock_sync:
  refresh_sec: 300        # How often to resync clocks in seconds
  warn_threshold_ms: 500  # Log warning if drift exceeds this many milliseconds
  kill_threshold_ms: 2000 # Terminate if drift exceeds this many milliseconds
  max_step_ms: 1000       # Max single adjustment step in milliseconds
  attempts: 5             # Number of sync attempts before giving up

kill_switch:
  feed_lag_ms: 60000       # Enter safe mode if worst feed lag exceeds this; 0 disables
  ws_failures: 100         # Enter safe mode if WS failures exceed this count; 0 disables
  error_rate: 0.2          # Enter safe mode if signal error rate exceeds this fraction; 0 disables
ttl:
  enabled: false
  ttl_seconds: 60
  out_csv: null
  dedup_persist: null
throttle:
  enabled: false              # disable throttling
  global:
    rps: 0.0                  # requests per second; 0 disables
    burst: 0                  # burst capacity
  symbol:
    rps: 0.0                  # per-symbol RPS limit
    burst: 0
  mode: drop                  # drop or queue
  queue:
    max_items: 0              # queue size when mode=queue
    ttl_ms: 0                 # item lifetime in ms
  time_source: "monotonic"
api:
  api_key: null
  api_secret: null
data:
  symbols: ["BTCUSDT"]
  timeframe: "1m"
# Optional path to 168 hourly liquidity multipliers (indexed by UTC hour-of-week;
# values clamped to [0.1, 10.0])
liquidity_seasonality_path: "configs/liquidity_latency_seasonality.json"
# Optional SHA256 hash of the above liquidity multipliers for integrity checking
liquidity_seasonality_hash: null
# Optional path to 168 hourly liquidity overrides multiplied with the above multipliers
liquidity_seasonality_override_path: null
# Optional path to 168 hourly latency multipliers (indexed by UTC hour-of-week;
# values clamped to [0.1, 10.0])
latency_seasonality_path: "configs/liquidity_latency_seasonality.json"
# Set false to ignore liquidity and latency multipliers
use_seasonality: true
latency:
  base_ms: 250
  jitter_ms: 50
  spike_p: 0.01
  spike_mult: 5.0
  timeout_ms: 2500
  retries: 1
  seed: 0  # RNG seed; seasonality multipliers do not affect RNG state
components:
  market_data:
    target: impl_binance_public:BinancePublicBarSource
    params:
      timeframe: "1m"
  executor:
    target: impl_sim_executor:SimExecutor
    params:
      symbol: "BTCUSDT"
  feature_pipe:
    target: feature_pipe:FeaturePipe
    params: {}
  policy:
    target: strategies.momentum:MomentumStrategy
    params: {}
  risk_guards:
    target: impl_risk_basic:RiskBasicImpl
    params: {}
