mode: live
run_id: live-run
logs_dir: logs
artifacts_dir: artifacts
api:
  api_key: null
  api_secret: null
data:
  symbols: ["BTCUSDT"]
  timeframe: "1m"
# Optional path to 168 hourly liquidity multipliers (indexed by UTC hour-of-week)
liquidity_seasonality_path: "configs/liquidity_latency_seasonality.json"
# Optional path to 168 hourly overrides multiplied with the above multipliers
liquidity_seasonality_override_path: null
use_seasonality: true  # set false to ignore liquidity/spread multipliers
latency:
  base_ms: 250
  jitter_ms: 50
  spike_p: 0.01
  spike_mult: 5.0
  timeout_ms: 2500
  retries: 1
  seed: 0  # RNG seed; seasonality multipliers do not affect RNG state
  seasonality_path: "configs/liquidity_latency_seasonality.json"  # UTC hour-of-week
  seasonality_override_path: null
  use_seasonality: true
components:
  market_data:
    target: impl_binance_public:BinancePublicBarSource
    params:
      timeframe: "1m"
  executor:
    target: impl_sim_executor:SimExecutor
    params:
      symbol: "BTCUSDT"
  feature_pipe:
    target: feature_pipe:FeaturePipe
    params: {}
  policy:
    target: strategies.momentum:MomentumStrategy
    params: {}
  risk_guards:
    target: impl_risk_basic:RiskBasicImpl
    params: {}
