mode: sim
run_id: sim-run
logs_dir: logs
artifacts_dir: artifacts
data:
  symbols: ["BTCUSDT"]
  timeframe: "1m"
components:
  market_data:
    target: impl_offline_data:OfflineCSVBarSource
    params:
      paths: ["data/sample.csv"]
      timeframe: "1m"
  executor:
    target: impl_sim_executor:SimExecutor
    params:
      symbol: "BTCUSDT"
  feature_pipe:
    target: offline_feature_pipe:OfflineFeaturePipe
    params: {}
  strategy:
    target: momentum:MomentumStrategy
    params: {}
  risk_guards:
    target: impl_risk_basic:RiskBasicImpl
    params: {}
  backtest_engine:
    target: service_backtest:ServiceBacktest
    params: {}
