mode: live
run_id: live-run
logs_dir: logs
artifacts_dir: artifacts
api:
  api_key: null
  api_secret: null
data:
  symbols: ["BTCUSDT"]
  timeframe: "1m"
components:
  market_data:
    target: impl_binance_public:BinancePublicBarSource
    params:
      timeframe: "1m"
  executor:
    target: impl_sim_executor:SimExecutor
    params:
      symbol: "BTCUSDT"
  feature_pipe:
    target: feature_pipe:FeaturePipe
    params: {}
  strategy:
    target: strategies.momentum:MomentumStrategy
    params: {}
  risk_guards:
    target: impl_risk_basic:RiskBasicImpl
    params: {}
