# Standalone execution configuration overrides
execution:
  intrabar_price_model: null
  timeframe_ms: null
  use_latency_from: null
  latency_constant_ms: null
  bridge:
    intrabar_price_model: null
    timeframe_ms: null
    use_latency_from: null
    latency_constant_ms: null
