rest_budget:
  enabled: true
  global: { qps: 8, burst: 16, jitter_ms: 50, cooldown_sec: 5 }
  endpoints:
    klines: { qps: 5, burst: 10 }
    exchangeInfo: { qps: 0.1, burst: 1, min_refresh_days: 1 }
  cache: { dir: "cache/http", ttl_days: 7, mode: "read_write" }
  checkpoint: { enabled: true, path: "state/offline_checkpoint.json" }
  concurrency: { workers: 4, batch_size: 500 }
  dynamic_from_headers: false
  shuffle_symbols: true
