# Operational settings for the runtime environment
clock_sync:
  refresh_sec: 300        # How often to resync clocks in seconds
  warn_threshold_ms: 500  # Log warning if drift exceeds this many milliseconds
  kill_threshold_ms: 2000 # Terminate if drift exceeds this many milliseconds
  max_step_ms: 1000       # Max single adjustment step in milliseconds
  attempts: 5             # Number of sync attempts before giving up

ws_dedup:
  enabled: true
  persist_path: state/last_bar_seen.json
  log_skips: true

ttl:
  enabled: false
  ttl_seconds: 60
  out_csv: null
  dedup_persist: null

throttle:
  enabled: false              # disable throttling
  global:
    rps: 0.0                  # requests per second; 0 disables
    burst: 0                  # burst capacity
  symbol:
    rps: 0.0                  # per-symbol RPS limit
    burst: 0
  mode: drop                  # drop or queue
  queue:
    max_items: 0              # queue size when mode=queue
    ttl_ms: 0                 # item lifetime in ms
  time_source: "monotonic"

runtime:
  queue:
    capacity: 1000            # event bus capacity; 0 for unbounded
    drop_policy: newest       # "newest" drops incoming, "oldest" drops oldest

