# Operational settings for the runtime environment
clock_sync:
  refresh_sec: 300        # How often to resync clocks in seconds
  warn_threshold_ms: 500  # Log warning if drift exceeds this many milliseconds
  kill_threshold_ms: 2000 # Terminate if drift exceeds this many milliseconds
  max_step_ms: 1000       # Max single adjustment step in milliseconds
  attempts: 5             # Number of sync attempts before giving up

