# Default quantizer configuration shared across run modes.
quantizer:
  filters_path: "data/binance_filters.json"
  # Flip the strict/enforce flags below to false to restore legacy permissive behaviour.
  strict: true
  enforce_percent_price_by_side: true
  auto_refresh_days: 30
  refresh_on_start: false
